Section "Device"
    Identifier "ST7789"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
    Option "ShadowFB" "off"
EndSection

Section "Device"
    Identifier "HDMI"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card0"
EndSection

Section "Screen"
    Identifier "LCD"
    Device "ST7789"
    DefaultDepth 16
    SubSection "Display"
        Depth 16
        Modes "320x170"
    EndSubSection
EndSection

Section "Screen"
    Identifier "HDMI"
    Device "HDMI"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1920x1080"
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "ZeroDay"
    Screen 0 "LCD" 0 0
    Screen 1 "HDMI" RightOf "LCD"
EndSection

Section "InputClass"
    Identifier "CardputerZero Built-in Keyboard"
    MatchProduct "tca8418"
    MatchDevicePath "/dev/input/by-path/platform-3f804000.i2c-event*"
    Driver "libinput"
    Option "xkb_model" "cardputer"
    Option "xkb_layout" "us"
EndSection

Section "InputClass"
    Identifier "USB Keyboard"
    MatchIsKeyboard "on"
    MatchDriver "libinput"
    MatchUSBID "*:*"
    Driver "libinput"
    Option "xkb_layout" "us"
EndSection